spring:
  rabbitmq:
    username: drawsee-test
    password: drawsee-test
    virtual-host: /drawsee-test
  data:
    redis:
      database: 2

drawsee:
  mysql:
    database: drawsee-test
  rabbitmq:
    aiConfig:
      queueCount: 2
      queueConcurrency: 2-4
    animationConfig:
      queueCount: 2