package cn.yifan.drawsee.converter;

import cn.yifan.drawsee.pojo.entity.CircuitDesign;
import cn.yifan.drawsee.pojo.entity.CircuitDesign.*;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;
import java.util.stream.Collectors;

@Slf4j
@Component
public class SpiceConverter {
    // 节点映射表，用于记录每个端口对应的节点编号
    private Map<String, String> nodeMap;
    private static final String GROUND_NODE = "0";

    // 支持的元件类型及其处理函数映射
    private final Map<String, Function<CircuitElement, String>> componentHandlers;

    public SpiceConverter() {
        this.nodeMap = new ConcurrentHashMap<>();
        this.componentHandlers = new HashMap<>();
        initComponentHandlers();
    }

    private void initComponentHandlers() {
        componentHandlers.put("resistor", this::resistorToSpice);
        componentHandlers.put("capacitor", this::capacitorToSpice);
        componentHandlers.put("inductor", this::inductorToSpice);
        componentHandlers.put("dc_source", this::dcSourceToSpice);
        componentHandlers.put("ac_source", this::acSourceToSpice);
        componentHandlers.put("diode", this::diodeToSpice);
        componentHandlers.put("transistor_npn", this::npnTransistorToSpice);
        componentHandlers.put("transistor_pnp", this::pnpTransistorToSpice);
        componentHandlers.put("opamp", this::opampToSpice);
    }

    public String generateNetlist(CircuitDesign design) {
        // 重置节点映射
        this.nodeMap = new ConcurrentHashMap<>();
        
        // 初始化网表
        List<String> netlistLines = new ArrayList<>();
        netlistLines.add("* " + design.getMetadata().getTitle());
        netlistLines.add("* Generated by DrawSee Circuit Java");
        
        // 预处理连接信息，建立节点映射
        buildNodeMap(design.getConnections());
        
        // 处理元件定义
        List<String> componentLines = processComponents(design.getElements());
        netlistLines.addAll(componentLines);
        
        // 添加分析指令
        netlistLines.add(".end");
        
        return String.join("\n", netlistLines);
    }

    private void buildNodeMap(List<CircuitConnection> connections) {
        int nodeCounter = 1; // 从1开始编号，0保留给接地节点
        
        // 创建等价类集合，将连接的端口归为同一组
        Map<String, Set<String>> equivalenceClasses = new HashMap<>();
        
        for (CircuitConnection conn : connections) {
            String sourceKey = conn.getSource().getElementId() + ":" + conn.getSource().getPortId();
            String targetKey = conn.getTarget().getElementId() + ":" + conn.getTarget().getPortId();
            
            // 查找现有的等价类
            String sourceClass = null;
            String targetClass = null;
            
            for (Map.Entry<String, Set<String>> entry : equivalenceClasses.entrySet()) {
                if (entry.getValue().contains(sourceKey)) {
                    sourceClass = entry.getKey();
                }
                if (entry.getValue().contains(targetKey)) {
                    targetClass = entry.getKey();
                }
            }
            
            // 处理等价类合并或创建
            if (sourceClass != null && targetClass != null) {
                if (!sourceClass.equals(targetClass)) {
                    // 合并两个等价类
                    equivalenceClasses.get(sourceClass).addAll(equivalenceClasses.get(targetClass));
                    equivalenceClasses.remove(targetClass);
                }
            } else if (sourceClass != null) {
                // 将目标添加到源的等价类
                equivalenceClasses.get(sourceClass).add(targetKey);
            } else if (targetClass != null) {
                // 将源添加到目标的等价类
                equivalenceClasses.get(targetClass).add(sourceKey);
            } else {
                // 创建新的等价类
                String newClassId = "class_" + nodeCounter++;
                Set<String> newClass = new HashSet<>();
                newClass.add(sourceKey);
                newClass.add(targetKey);
                equivalenceClasses.put(newClassId, newClass);
            }
        }
        
        // 为每个等价类分配节点编号
        for (Set<String> portSet : equivalenceClasses.values()) {
            String nodeId = "N" + nodeCounter++;
            for (String portKey : portSet) {
                nodeMap.put(portKey, nodeId);
            }
        }
    }

    private List<String> processComponents(List<CircuitElement> elements) {
        return elements.stream()
                .map(elem -> {
                    Function<CircuitElement, String> handler = componentHandlers.get(elem.getType());
                    if (handler != null) {
                        return handler.apply(elem);
                    } else {
                        return "* Unsupported component: " + elem.getId() + " (type: " + elem.getType() + ")";
                    }
                })
                .collect(Collectors.toList());
    }

    private String getNodeId(String elementId, String portId) {
        String key = elementId + ":" + portId;
        return nodeMap.getOrDefault(key, GROUND_NODE);
    }

    private String resistorToSpice(CircuitElement elem) {
        String n1 = getNodeId(elem.getId(), elem.getPorts().get(0).getId());
        String n2 = getNodeId(elem.getId(), elem.getPorts().get(1).getId());
        
        // 获取电阻值
        double resistance = (Double) elem.getProperties().getOrDefault("resistance", 1000.0);  // 默认1kΩ
        
        String cleanId = elem.getId().replace("-", "_");
        
        return String.format("R%s %s %s %s", cleanId, n1, n2, resistance);
    }

    private String capacitorToSpice(CircuitElement elem) {
        String n1 = getNodeId(elem.getId(), elem.getPorts().get(0).getId());
        String n2 = getNodeId(elem.getId(), elem.getPorts().get(1).getId());
        
        // 获取电容值，单位为法拉
        double capacitance = (Double) elem.getProperties().getOrDefault("capacitance", 1e-6);  // 默认1μF
        
        String cleanId = elem.getId().replace("-", "_");
        
        return String.format("C%s %s %s %s", cleanId, n1, n2, capacitance);
    }

    private String inductorToSpice(CircuitElement elem) {
        String n1 = getNodeId(elem.getId(), elem.getPorts().get(0).getId());
        String n2 = getNodeId(elem.getId(), elem.getPorts().get(1).getId());
        
        // 获取电感值，单位为亨利
        double inductance = (Double) elem.getProperties().getOrDefault("inductance", 1e-3);  // 默认1mH
        
        String cleanId = elem.getId().replace("-", "_");
        
        return String.format("L%s %s %s %s", cleanId, n1, n2, inductance);
    }

    private String dcSourceToSpice(CircuitElement elem) {
        Port posPort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("pos"))
                .findFirst()
                .orElse(elem.getPorts().get(0));
                
        Port negPort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("neg"))
                .findFirst()
                .orElse(elem.getPorts().get(1));
        
        String n1 = getNodeId(elem.getId(), posPort.getId());
        String n2 = getNodeId(elem.getId(), negPort.getId());
        
        // 获取电压值
        double voltage = (Double) elem.getProperties().getOrDefault("voltage", 5.0);  // 默认5V
        
        String cleanId = elem.getId().replace("-", "_");
        
        return String.format("V%s %s %s DC %s", cleanId, n1, n2, voltage);
    }

    private String acSourceToSpice(CircuitElement elem) {
        Port posPort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("pos"))
                .findFirst()
                .orElse(elem.getPorts().get(0));
                
        Port negPort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("neg"))
                .findFirst()
                .orElse(elem.getPorts().get(1));
        
        String n1 = getNodeId(elem.getId(), posPort.getId());
        String n2 = getNodeId(elem.getId(), negPort.getId());
        
        // 获取电压幅值和频率
        double amplitude = (Double) elem.getProperties().getOrDefault("amplitude", 5.0);  // 默认5V
        double frequency = (Double) elem.getProperties().getOrDefault("frequency", 1000.0);  // 默认1kHz
        
        String cleanId = elem.getId().replace("-", "_");
        
        return String.format("V%s %s %s AC %s SIN(0 %s %s)", cleanId, n1, n2, amplitude, amplitude, frequency);
    }

    private String diodeToSpice(CircuitElement elem) {
        Port anodePort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("anode"))
                .findFirst()
                .orElse(elem.getPorts().get(0));
                
        Port cathodePort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("cathode"))
                .findFirst()
                .orElse(elem.getPorts().get(1));
        
        String n1 = getNodeId(elem.getId(), anodePort.getId());
        String n2 = getNodeId(elem.getId(), cathodePort.getId());
        
        // 使用默认二极管模型
        String model = (String) elem.getProperties().getOrDefault("model", "D1N4148");
        
        String cleanId = elem.getId().replace("-", "_");
        
        return String.format("D%s %s %s %s", cleanId, n1, n2, model);
    }

    private String npnTransistorToSpice(CircuitElement elem) {
        Port collectorPort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("collector"))
                .findFirst()
                .orElse(elem.getPorts().get(0));
                
        Port basePort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("base"))
                .findFirst()
                .orElse(elem.getPorts().get(1));
                
        Port emitterPort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("emitter"))
                .findFirst()
                .orElse(elem.getPorts().get(2));
        
        String nc = getNodeId(elem.getId(), collectorPort.getId());
        String nb = getNodeId(elem.getId(), basePort.getId());
        String ne = getNodeId(elem.getId(), emitterPort.getId());
        
        // 使用默认NPN模型
        String model = (String) elem.getProperties().getOrDefault("model", "Q2N3904");
        
        String cleanId = elem.getId().replace("-", "_");
        
        return String.format("Q%s %s %s %s %s", cleanId, nc, nb, ne, model);
    }

    private String pnpTransistorToSpice(CircuitElement elem) {
        Port collectorPort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("collector"))
                .findFirst()
                .orElse(elem.getPorts().get(0));
                
        Port basePort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("base"))
                .findFirst()
                .orElse(elem.getPorts().get(1));
                
        Port emitterPort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("emitter"))
                .findFirst()
                .orElse(elem.getPorts().get(2));
        
        String nc = getNodeId(elem.getId(), collectorPort.getId());
        String nb = getNodeId(elem.getId(), basePort.getId());
        String ne = getNodeId(elem.getId(), emitterPort.getId());
        
        // 使用默认PNP模型
        String model = (String) elem.getProperties().getOrDefault("model", "Q2N3906");
        
        String cleanId = elem.getId().replace("-", "_");
        
        return String.format("Q%s %s %s %s %s", cleanId, nc, nb, ne, model);
    }

    private String opampToSpice(CircuitElement elem) {
        Port inPlusPort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("in+"))
                .findFirst()
                .orElse(elem.getPorts().get(0));
                
        Port inMinusPort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("in-"))
                .findFirst()
                .orElse(elem.getPorts().get(1));
                
        Port outPort = elem.getPorts().stream()
                .filter(p -> p.getId().equals("out"))
                .findFirst()
                .orElse(elem.getPorts().get(2));
        
        String np = getNodeId(elem.getId(), inPlusPort.getId());
        String nm = getNodeId(elem.getId(), inMinusPort.getId());
        String no = getNodeId(elem.getId(), outPort.getId());
        
        // 使用默认运放模型
        String model = (String) elem.getProperties().getOrDefault("model", "LM741");
        
        String cleanId = elem.getId().replace("-", "_");
        
        return String.format("X%s %s %s %s %s", cleanId, np, nm, no, model);
    }
} 