package cn.yifan.drawsee.converter;

import cn.yifan.drawsee.pojo.entity.CircuitDesign;
import cn.yifan.drawsee.pojo.entity.CircuitDesign.CircuitConnection;
import cn.yifan.drawsee.pojo.entity.CircuitDesign.CircuitElement;
import cn.yifan.drawsee.pojo.entity.CircuitDesign.Port;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;
import java.util.stream.Collectors;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

/**
 * 电路SPICE网表转换器。
 *
 * <p>说明：
 * - 该转换器主要为 AI 电路分析提供结构化网表参考，不追求完整 SPICE 兼容性。
 * - 对示波器、电流表、电压表、地等非仿真元件，输出带节点信息的注释而不是 unsupported。
 */
@Slf4j
@Component
public class SpiceConverter {

  private static final String GROUND_NODE = "0";

  private Map<String, String> nodeMap;
  private final Map<String, Function<CircuitElement, String>> componentHandlers;

  public SpiceConverter() {
    this.nodeMap = new ConcurrentHashMap<>();
    this.componentHandlers = new HashMap<>();
    initComponentHandlers();
  }

  private void initComponentHandlers() {
    componentHandlers.put("resistor", this::resistorToSpice);
    componentHandlers.put("capacitor", this::capacitorToSpice);
    componentHandlers.put("inductor", this::inductorToSpice);
    componentHandlers.put("dc_source", this::dcSourceToSpice);
    componentHandlers.put("current_source", this::currentSourceToSpice);
    componentHandlers.put("ac_source", this::acSourceToSpice);
    componentHandlers.put("pulse_source", this::pulseSourceToSpice);
    componentHandlers.put("pwm_source", this::pwmSourceToSpice);
    componentHandlers.put("sine_source", this::sineSourceToSpice);
    componentHandlers.put("diode", this::diodeToSpice);
    componentHandlers.put("diode_zener", this::diodeToSpice);
    componentHandlers.put("diode_led", this::diodeToSpice);
    componentHandlers.put("diode_schottky", this::diodeToSpice);
    componentHandlers.put("bjt", this::npnTransistorToSpice);
    componentHandlers.put("bjt_pnp", this::pnpTransistorToSpice);
    componentHandlers.put("transistor_npn", this::npnTransistorToSpice);
    componentHandlers.put("transistor_pnp", this::pnpTransistorToSpice);
    componentHandlers.put("opamp", this::opampToSpice);

    componentHandlers.put("ground", this::measurementComment);
    componentHandlers.put("ammeter", this::measurementComment);
    componentHandlers.put("voltmeter", this::measurementComment);
    componentHandlers.put("oscilloscope", this::measurementComment);
    componentHandlers.put("wire", this::measurementComment);
    componentHandlers.put("junction", this::measurementComment);
  }

  public String generateNetlist(CircuitDesign design) {
    this.nodeMap = new ConcurrentHashMap<>();

    List<String> netlistLines = new ArrayList<>();
    String title =
        design != null && design.getMetadata() != null && design.getMetadata().getTitle() != null
            ? design.getMetadata().getTitle()
            : "Untitled Circuit";
    netlistLines.add("* " + title);
    netlistLines.add("* Generated by DrawSee Circuit Java");

    List<CircuitConnection> connections =
        design != null && design.getConnections() != null ? design.getConnections() : List.of();
    List<CircuitElement> elements =
        design != null && design.getElements() != null ? design.getElements() : List.of();
    buildNodeMap(connections, elements);

    netlistLines.addAll(processComponents(elements));
    netlistLines.add(".end");
    return String.join("\n", netlistLines);
  }

  private void buildNodeMap(List<CircuitConnection> connections, List<CircuitElement> elements) {
    Map<String, Set<String>> equivalenceClasses = new LinkedHashMap<>();
    Set<String> groundKeys = new HashSet<>();
    int classCounter = 1;
    int nodeCounter = 1;

    for (CircuitElement element : elements) {
      if (!"ground".equals(element.getType())) {
        continue;
      }
      for (Port port : safePorts(element)) {
        groundKeys.add(endpointKey(element.getId(), port.getId()));
      }
    }

    for (CircuitConnection conn : connections) {
      String sourceKey = endpointKey(conn.getSource().getElementId(), conn.getSource().getPortId());
      String targetKey = endpointKey(conn.getTarget().getElementId(), conn.getTarget().getPortId());

      String sourceClass = findClassId(equivalenceClasses, sourceKey);
      String targetClass = findClassId(equivalenceClasses, targetKey);

      if (sourceClass != null && targetClass != null) {
        if (!sourceClass.equals(targetClass)) {
          equivalenceClasses.get(sourceClass).addAll(equivalenceClasses.get(targetClass));
          equivalenceClasses.remove(targetClass);
        }
      } else if (sourceClass != null) {
        equivalenceClasses.get(sourceClass).add(targetKey);
      } else if (targetClass != null) {
        equivalenceClasses.get(targetClass).add(sourceKey);
      } else {
        String newClassId = "class_" + classCounter++;
        Set<String> newClass = new HashSet<>();
        newClass.add(sourceKey);
        newClass.add(targetKey);
        equivalenceClasses.put(newClassId, newClass);
      }
    }

    for (CircuitElement element : elements) {
      for (Port port : safePorts(element)) {
        String key = endpointKey(element.getId(), port.getId());
        if (groundKeys.contains(key)) {
          nodeMap.put(key, GROUND_NODE);
          continue;
        }
        if (findClassId(equivalenceClasses, key) == null) {
          String newClassId = "class_" + classCounter++;
          Set<String> isolated = new HashSet<>();
          isolated.add(key);
          equivalenceClasses.put(newClassId, isolated);
        }
      }
    }

    for (Set<String> portSet : equivalenceClasses.values()) {
      boolean isGround = portSet.stream().anyMatch(groundKeys::contains);
      String nodeId = isGround ? GROUND_NODE : "N" + nodeCounter++;
      for (String portKey : portSet) {
        nodeMap.put(portKey, nodeId);
      }
    }
  }

  private List<String> processComponents(List<CircuitElement> elements) {
    return elements.stream()
        .map(
            elem -> {
              Function<CircuitElement, String> handler = componentHandlers.get(elem.getType());
              if (handler != null) {
                return handler.apply(elem);
              }
              return "* Non-SPICE component: "
                  + displayName(elem)
                  + " ["
                  + elem.getId()
                  + "] (type: "
                  + elem.getType()
                  + ")";
            })
        .collect(Collectors.toList());
  }

  private String resistorToSpice(CircuitElement elem) {
    List<Port> ports = pickPorts(elem, "a", "b");
    String n1 = getNodeId(elem.getId(), ports.get(0).getId());
    String n2 = getNodeId(elem.getId(), ports.get(1).getId());
    double resistance = getDouble(elem, "resistance", getDouble(elem, "value", 1000.0));
    return String.format("R%s %s %s %s", reference("R", elem), n1, n2, resistance);
  }

  private String capacitorToSpice(CircuitElement elem) {
    List<Port> ports = pickPorts(elem, "a", "b");
    String n1 = getNodeId(elem.getId(), ports.get(0).getId());
    String n2 = getNodeId(elem.getId(), ports.get(1).getId());
    double capacitance = getDouble(elem, "capacitance", getDouble(elem, "value", 1e-6));
    return String.format("C%s %s %s %s", reference("C", elem), n1, n2, capacitance);
  }

  private String inductorToSpice(CircuitElement elem) {
    List<Port> ports = pickPorts(elem, "a", "b");
    String n1 = getNodeId(elem.getId(), ports.get(0).getId());
    String n2 = getNodeId(elem.getId(), ports.get(1).getId());
    double inductance = getDouble(elem, "inductance", getDouble(elem, "value", 1e-3));
    return String.format("L%s %s %s %s", reference("L", elem), n1, n2, inductance);
  }

  private String dcSourceToSpice(CircuitElement elem) {
    Port positive = pickPort(elem, "positive", 0);
    Port negative = pickPort(elem, "negative", 1);
    String n1 = getNodeId(elem.getId(), positive.getId());
    String n2 = getNodeId(elem.getId(), negative.getId());
    double voltage = getDouble(elem, "voltage", getDouble(elem, "value", 5.0));
    return String.format("V%s %s %s DC %s", reference("V", elem), n1, n2, voltage);
  }

  private String currentSourceToSpice(CircuitElement elem) {
    Port positive = pickPort(elem, "positive", 0);
    Port negative = pickPort(elem, "negative", 1);
    String n1 = getNodeId(elem.getId(), positive.getId());
    String n2 = getNodeId(elem.getId(), negative.getId());
    double current = getDouble(elem, "current", getDouble(elem, "value", 0.01));
    return String.format("I%s %s %s DC %s", reference("I", elem), n1, n2, current);
  }

  private String acSourceToSpice(CircuitElement elem) {
    Port positive = pickPort(elem, "positive", 0);
    Port negative = pickPort(elem, "negative", 1);
    String n1 = getNodeId(elem.getId(), positive.getId());
    String n2 = getNodeId(elem.getId(), negative.getId());
    double amplitude = getDouble(elem, "amplitude", 1.0);
    double frequency = getDouble(elem, "frequency", 1000.0);
    return String.format(
        "V%s %s %s SIN(0 %s %s)", reference("VAC", elem), n1, n2, amplitude, frequency);
  }

  private String pulseSourceToSpice(CircuitElement elem) {
    Port positive = pickPort(elem, "positive", 0);
    Port negative = pickPort(elem, "negative", 1);
    String n1 = getNodeId(elem.getId(), positive.getId());
    String n2 = getNodeId(elem.getId(), negative.getId());
    double v1 = getDouble(elem, "v1", 0.0);
    double v2 = getDouble(elem, "v2", 5.0);
    double td = getDouble(elem, "td", 0.0);
    double tr = getDouble(elem, "tr", 1e-9);
    double tf = getDouble(elem, "tf", 1e-9);
    double pw = getDouble(elem, "pw", 1e-6);
    double per = getDouble(elem, "per", 2e-6);
    return String.format(
        "V%s %s %s PULSE(%s %s %s %s %s %s %s)",
        reference("VPULSE", elem), n1, n2, v1, v2, td, tr, tf, pw, per);
  }

  private String pwmSourceToSpice(CircuitElement elem) {
    Port positive = pickPort(elem, "positive", 0);
    Port negative = pickPort(elem, "negative", 1);
    String n1 = getNodeId(elem.getId(), positive.getId());
    String n2 = getNodeId(elem.getId(), negative.getId());
    double low = getDouble(elem, "vlow", 0.0);
    double high = getDouble(elem, "vhigh", 5.0);
    double freqHz = getDouble(elem, "freqHz", 1000.0);
    double duty = getDouble(elem, "duty", 0.5);
    double period = freqHz > 0 ? 1.0 / freqHz : 1e-3;
    double width = Math.max(period * duty, 1e-9);
    return String.format(
        "V%s %s %s PULSE(%s %s 0 1n 1n %s %s)",
        reference("VPWM", elem), n1, n2, low, high, width, period);
  }

  private String sineSourceToSpice(CircuitElement elem) {
    Port positive = pickPort(elem, "positive", 0);
    Port negative = pickPort(elem, "negative", 1);
    String n1 = getNodeId(elem.getId(), positive.getId());
    String n2 = getNodeId(elem.getId(), negative.getId());
    double offset = getDouble(elem, "vo", 0.0);
    double amplitude = getDouble(elem, "va", 1.0);
    double frequency = getDouble(elem, "freq", 1000.0);
    double phase = getDouble(elem, "phase", 0.0);
    return String.format(
        "V%s %s %s SIN(%s %s %s 0 %s)",
        reference("VSIN", elem), n1, n2, offset, amplitude, frequency, phase);
  }

  private String diodeToSpice(CircuitElement elem) {
    Port anode = pickPort(elem, "anode", 0);
    Port cathode = pickPort(elem, "cathode", 1);
    String n1 = getNodeId(elem.getId(), anode.getId());
    String n2 = getNodeId(elem.getId(), cathode.getId());
    String model = getString(elem, "model", "DDEFAULT");
    return String.format("D%s %s %s %s", reference("D", elem), n1, n2, model);
  }

  private String npnTransistorToSpice(CircuitElement elem) {
    Port base = pickPort(elem, "base", 0);
    Port collector = pickPort(elem, "collector", 1);
    Port emitter = pickPort(elem, "emitter", 2);
    String nb = getNodeId(elem.getId(), base.getId());
    String nc = getNodeId(elem.getId(), collector.getId());
    String ne = getNodeId(elem.getId(), emitter.getId());
    String model = getString(elem, "model", "Q2N3904");
    return String.format("Q%s %s %s %s %s", reference("Q", elem), nc, nb, ne, model);
  }

  private String pnpTransistorToSpice(CircuitElement elem) {
    Port base = pickPort(elem, "base", 0);
    Port collector = pickPort(elem, "collector", 1);
    Port emitter = pickPort(elem, "emitter", 2);
    String nb = getNodeId(elem.getId(), base.getId());
    String nc = getNodeId(elem.getId(), collector.getId());
    String ne = getNodeId(elem.getId(), emitter.getId());
    String model = getString(elem, "model", "Q2N3906");
    return String.format("Q%s %s %s %s %s", reference("QP", elem), nc, nb, ne, model);
  }

  private String opampToSpice(CircuitElement elem) {
    Port inPlus = pickPort(elem, "input1", 0);
    Port inMinus = pickPort(elem, "input2", 1);
    Port out = pickPort(elem, "output", 2);
    String np = getNodeId(elem.getId(), inPlus.getId());
    String nm = getNodeId(elem.getId(), inMinus.getId());
    String no = getNodeId(elem.getId(), out.getId());
    String model = getString(elem, "model", "LM741");
    return String.format("X%s %s %s %s %s", reference("U", elem), np, nm, no, model);
  }

  private String measurementComment(CircuitElement elem) {
    String nets =
        safePorts(elem).stream()
            .map(port -> getNodeId(elem.getId(), port.getId()))
            .collect(Collectors.joining(", "));
    return "* Instrument "
        + displayName(elem)
        + " ["
        + elem.getId()
        + "] (type: "
        + elem.getType()
        + ", nets: "
        + nets
        + ")";
  }

  private String endpointKey(String elementId, String portId) {
    return elementId + ":" + portId;
  }

  private String findClassId(Map<String, Set<String>> equivalenceClasses, String key) {
    for (Map.Entry<String, Set<String>> entry : equivalenceClasses.entrySet()) {
      if (entry.getValue().contains(key)) {
        return entry.getKey();
      }
    }
    return null;
  }

  private String getNodeId(String elementId, String portId) {
    return nodeMap.getOrDefault(endpointKey(elementId, portId), GROUND_NODE);
  }

  private List<Port> safePorts(CircuitElement elem) {
    return elem.getPorts() != null ? elem.getPorts() : List.of();
  }

  private Port pickPort(CircuitElement elem, String preferredId, int fallbackIndex) {
    return safePorts(elem).stream()
        .filter(port -> preferredId.equals(port.getId()))
        .findFirst()
        .orElseGet(
            () ->
                safePorts(elem).isEmpty()
                    ? new Port(preferredId, preferredId, "bidirectional", null)
                    : safePorts(elem).get(Math.min(fallbackIndex, safePorts(elem).size() - 1)));
  }

  private List<Port> pickPorts(CircuitElement elem, String firstId, String secondId) {
    List<Port> ports = safePorts(elem);
    if (ports.size() >= 2) {
      return List.of(
          pickPort(elem, firstId, 0),
          pickPort(elem, secondId, 1));
    }
    if (ports.size() == 1) {
      return List.of(ports.get(0), ports.get(0));
    }
    return List.of(
        new Port(firstId, firstId, "bidirectional", null),
        new Port(secondId, secondId, "bidirectional", null));
  }

  private String displayName(CircuitElement elem) {
    if (elem.getLabel() != null && !elem.getLabel().isBlank()) {
      return elem.getLabel().trim();
    }
    return elem.getId();
  }

  private String reference(String prefix, CircuitElement elem) {
    String raw = displayName(elem).replaceAll("[^0-9A-Za-z_]", "_");
    if (raw.isBlank()) {
      raw = elem.getId().replaceAll("[^0-9A-Za-z_]", "_");
    }
    if (raw.isBlank()) {
      raw = "X";
    }
    String upperPrefix = prefix.toUpperCase();
    String upperRaw = raw.toUpperCase();
    if (upperRaw.startsWith(upperPrefix)) {
      return raw;
    }
    return upperPrefix + raw;
  }

  private double getDouble(CircuitElement elem, String key, double fallback) {
    if (elem.getProperties() != null) {
      Object raw = elem.getProperties().get(key);
      if (raw instanceof Number number) {
        return number.doubleValue();
      }
      if (raw instanceof String text) {
        try {
          return Double.parseDouble(text.trim());
        } catch (NumberFormatException ignore) {
          log.debug("无法将属性 {}={} 解析为数字", key, text);
        }
      }
    }
    if ("value".equals(key) && elem.getValue() != null) {
      try {
        return Double.parseDouble(elem.getValue().trim());
      } catch (NumberFormatException ignore) {
        log.debug("无法将元件值 {} 解析为数字", elem.getValue());
      }
    }
    return fallback;
  }

  private String getString(CircuitElement elem, String key, String fallback) {
    if (elem.getProperties() != null) {
      Object raw = elem.getProperties().get(key);
      if (raw != null) {
        String text = String.valueOf(raw).trim();
        if (!text.isBlank()) {
          return text;
        }
      }
    }
    return fallback;
  }
}
